---
trust-domain: mozilla
task-priority: highest

taskgraph:
  repositories:
    project:
      name: project

workers:
  aliases:
    '[bt]-linux':
      provisioner: '{trust-domain}-{level}'
      implementation: docker-worker
      os: linux
      worker-type: '{alias}-gcp'
    images:
      provisioner: '{trust-domain}-{level}'
      implementation: docker-worker
      os: linux
      worker-type: '{alias}-gcp'
