---
trust-domain: mozilla
task-priority: highest

taskgraph:
  cached-task-prefix: mozilla.v2.firefox-ci-template
  repositories:
    firefox-ci-template:
      name: Firefox-CI Template

workers:
  aliases:
    '[bt]-linux':
      provisioner: '{trust-domain}-{level}'
      implementation: docker-worker
      os: linux
      worker-type: '{alias}-gcp'
    images:
      provisioner: '{trust-domain}-{level}'
      implementation: docker-worker
      os: linux
      worker-type: '{alias}-gcp'
